name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3 # versi칩n m치s reciente
        with:
          username: ${{ secrets.DOCKER_USER}}
          password: ${{ secrets.DOCKER_PASS}}

      - name: Checkout
        uses: actions/checkout@v4 # versi칩n m치s reciente

      - name: Run tests
        run: |
          docker compose run --rm app sh -c "python manage.py test"

      - name: Run linting
        run: |
          docker compose run --rm app sh -c "flake8"
