name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Docker
        run: docker --version

      - name: Verificar Docker Compose
        run: docker compose version

      - name: Login to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Checkout
        uses: actions/checkout@v4 

      - name: Run tests
        run: |
          docker compose run --rm app sh -c "python manage.py test"

      - name: Run linting
        run: |
          docker compose run --rm app sh -c "flake8"
